
version: '3.3'

services:
    nginx:
        build: 
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./wp:/var/www/
        links:
            - php-fpm
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        container_name: mysql
        environment:

            - MYSQL_ROOT_PASSWORD=mypassword
            - MYSQL_DATABASE=wp_test
            - MYSQL_USER=testtest
            - MYSQL_PASSWORD=testtest

        volumes:
            - ./mysql/db:/var/lib/mysql   
    php-fpm:
        build: 
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        container_name: php-fpm
        volumes:
            - ./wp:/var/www/
        links:
            - mysql

